export const ACTION_ADD_NOTICE = 'ACTION_ADD_NOTICE';
export const ACTION_REMOVE_NOTE = 'ACTION_REMOVE_NOTE';
export const ACTION_SAVE_NOTICE = 'ACTION_SAVE_NOTICE';
export const ACTION_GO_TO_NOTICE = 'ACTION_GO_TO_NOTICE';
